#!/usr/bin/env perl

use strict;
use warnings;
use 5.010;

my %keys = (
    'total' => 'LINE3',
    'atom' => 'AREA',
    'processes' => 'STACK',
    'binary' => 'STACK',
    'ets' => 'STACK',
);

my $node = 'test@marie';
my $cookie = 'node';

# run
if ($#ARGV < 0) {
    my $data = `erl_call -c $cookie -a 'erlang memory' -n $node`;
    $data =~ s/[^a-z0-9_\,]//g;
    my %parsed = split(",", $data);

    for my $key (keys %keys) {
        say "${key}.value $parsed{$key}";
    }
}
else {
    # config
    if ($ARGV[0] eq "config") {
        my $config = <<CF;
graph_args --base 1024 -l 0
graph_vlabel Bytes
graph_title Erlang node '$node' memory usage
graph_category erlang
graph_order atom ets processes binary total
CF
        print $config;
        for my $key (keys %keys) {
            say "${key}.label ${key}";
            say "${key}.draw $keys{$key}";
        }
    }
}
